on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Should success
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains [ci skip] in message body in merge commit
          ref: '0928dd4ccbb9a9d5e39791011e1ec5792c495848'
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@master
      - name: Check env
        run: |
          echo "CI_SKIP is $CI_SKIP"
          echo "CI_SKIP_NOT is $CI_SKIP_NOT"
          if [[ "$CI_SKIP" != true ]]; then
            echo "The CI_SKIP env should be set to true, but it is: $CI_SKIP"
            exit 1
          fi
          if [[ "$CI_SKIP_NOT" != false ]]; then
            echo "The CI_SKIP_NOT env should be set to false, but it is: $CI_SKIP_NOT"
            exit 2
          fi
      - name: Check if expression CI_SKIP
        if: ${{ env.CI_SKIP == 'false' }}
        run: |
          echo "This step should not be executed"
          echo "CI_SKIP is $CI_SKIP"
          exit 3
      - name: Check if expression CI_SKIP_NOT
        if: ${{ env.CI_SKIP_NOT == 'true' }}
        run: |
          echo "This step should not be executed"
          echo "CI_SKIP_NOT is $CI_SKIP_NOT"
          exit 4

